In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as md
import os
import mne
import random

In [2]:
MDD_dataset_Filenames = os.listdir('./data/MDD')
H_dataset_Filenames = os.listdir('./data/H')
MDD_dataset_list = []
H_dataset_list = []

for filename in MDD_dataset_Filenames:
    data = mne.io.read_raw_edf('./dataset/EC/' + str(filename))
    MDD_dataset_list.append(data)  
    
for filename in H_dataset_Filenames:
    data = mne.io.read_raw_edf('./dataset/EC/' + str(filename))
    H_dataset_list.append(data)  



Extracting EDF parameters from C:\python\study\4월3주\depression\dataset\EC\MDD S1 EC.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Extracting EDF parameters from C:\python\study\4월3주\depression\dataset\EC\MDD S10 EC.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Extracting EDF parameters from C:\python\study\4월3주\depression\dataset\EC\MDD S11 EC.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Extracting EDF parameters from C:\python\study\4월3주\depression\dataset\EC\MDD S12 EC.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Extracting EDF parameters from C:\python\study\4월3주\depression\dataset\EC\MDD S13 EC.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Extracting EDF parameters from C:\python\study\4월3주\depression\dataset\EC\MDD S14 EC.edf...
EDF file detected
Setting channel 

In [4]:
MDD_dataframe_list = [] #MDD 환자의 데이터프레임 리스트
H_dataframe_list = [] #건강한 사람의 데이터프레임 리스트
for raw in MDD_dataset_list:
    raw_data = raw.get_data(return_times=True)
    channels = raw.ch_names
    T_data = np.transpose(raw_data[0])
    time = np.transpose(raw_data[1])
    temp = pd.DataFrame(T_data, columns = channels, index = time)
    MDD_dataframe_list.append(temp)
    
for raw in H_dataset_list:
    raw_data = raw.get_data(return_times=True)
    channels = raw.ch_names
    T_data = np.transpose(raw_data[0])
    time = np.transpose(raw_data[1])
    temp = pd.DataFrame(T_data, columns = channels, index = time)
    H_dataframe_list.append(temp)

MDD_dataframe_list[23].rename(columns = {'E F3-Ref': 'F3'}, inplace = True)

In [34]:
X = []
y = []

In [45]:
for i in range(len(MDD_dataframe_list)):
    a = MDD_dataframe_list[i]
    #데이터 클린징
    a.F3 = a.F3[a.F3 > -0.0005]
    a = a.fillna(method='ffill')
    fft = np.fft.fft(a['F3'])
    X.append(fft)
    y.append(1)
    
  
    

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [38]:
combinedDict = list(zip(X, y))
random.shuffle(combinedDict)
X[:], y[:] = zip(*combinedDict)

In [40]:
X = np.asarray(X)
y = np.array(y)

In [56]:
X.reshape((-1, )).shape

(1, 30)

array([array([ 1.90800000e-03+0.00000000e+00j, -3.47999914e-04-6.56490085e-05j,
       -4.03775530e-05+2.08309585e-04j, ...,
       -3.35264510e-04-1.25124121e-04j, -4.03775530e-05-2.08309585e-04j,
       -3.47999914e-04+6.56490085e-05j]),
       array([ 0.006986  +0.j        , -0.00330351+0.00533055j,
       -0.00477856-0.00129966j, ...,  0.00136779-0.00034316j,
       -0.00477856+0.00129966j, -0.00330351-0.00533055j]),
       array([ 1.60000000e-03+0.00000000e+00j, -3.03536698e-05-5.38778943e-05j,
        5.70356802e-05+1.64448746e-04j, ...,
       -1.81983017e-04-6.14077262e-05j,  5.70356802e-05-1.64448746e-04j,
       -3.03536698e-05+5.38778943e-05j]),
       array([ 2.56000000e-03+0.j        , -3.38581229e-04-0.00021692j,
        1.29294746e-05+0.00019567j, ..., -1.77079729e-04+0.00016408j,
        1.29294746e-05-0.00019567j, -3.38581229e-04+0.00021692j]),
       array([1.42500000e-03+0.00000000e+00j, 1.21781219e-04+9.16660436e-05j,
       1.29545166e-04-5.30974541e-05j, ...,
    